import { Inter } from "next/font/google";
import "./globals.css";
import RootHeader from "./(common-root-layout)/RootHeader";
import RootFooter from "./(common-root-layout)/RootFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <RootHeader />
        {children}
      <RootFooter />
      </body>
    </html>
  );
}
